### PR TITLE
bugfixes

### LINKED ISSUE #197: Unexpected behaviour @Fallback method calls with @CircuitBreaker
MP FT does not behave correctly in case when there is @CircuitBreaker, @Fallback, @Retry and @Asynchronous on service method. @CircuitBreaker does not get opened based on its configuration and @Fallback method is called with incorrect value. 

Test scenario:
* Deploy MP FT service with:
```java
    @Asynchronous
    @Retry(retryOn = IOException.class)
    @CircuitBreaker(failOn = IOException.class, requestVolumeThreshold = 5, successThreshold = 3, delay = 2, delayUnit = ChronoUnit.SECONDS, failureRatio = 0.75)
    @Fallback(fallbackMethod = "processFallback")
    public CompletionStage<MyConnection> retryCircuitBreaker(int counter) throws IOException {
        System.out.println("retryCircuitBreaker - called - " + counter);
        if (counter % 4 != 0) { // 3/4 requests trigger IOException
            System.out.println("retryCircuitBreaker - called - " + counter + " throwing exception");
            throw new IOException("Simulated IOException");
        }
        System.out.println("retryCircuitBreaker - called - " + counter + " success");
        return CompletableFuture.completedFuture(new MyConnection() {
            @Override
            public String getData() {
                return "Hello from @Retry @CircuitBreaker method" + counter;
            }
        });
    }

    private CompletionStage<MyConnection> processFallback(int counter) {
        System.out.println("processFallback - returned url counter: " + counter);
        return CompletableFuture.completedFuture(new MyConnection() {
            @Override
            public String getData() {
                return "Fallback Hello" + counter;
            }
        });
    }
```

* Sends 16 parallel requests. Every 4th requests pass (including 0th one as there is modulo 4), and 12 invocations fail on IOException.
* Try on more request and check that @Fallback method was called as circuit is open

Expected result:
Circuit gets opened and @Fallback method is called. 

Actual Result:
Circuit is not opened and @Fallback method is called. 

https://issues.redhat.com/browse/WFWIP-307

### LINKED ISSUE #198: Unexpected behaviour @Fallback method calls with @Bulkhead
MP FT does behave correctly in case when there is @Bulkhead, @Timeout and @Fallback and @Asynchronous on service method. Some of requests do not go to fallback method but end with InterruptedException.

Test scenario:

Deploy MP FT service with:
```java
    @Asynchronous
    @Bulkhead(value = 15, waitingTaskQueue = 15)
    @Timeout(value = 1000)
    @Fallback(fallbackMethod = "processFallback")
    public CompletionStage<MyConnection> bulkheadTimeout(boolean fail) throws InterruptedException {
        if (fail) {
            Thread.sleep(2000);
        }
        return CompletableFuture.completedFuture(new MyConnection() {
            @Override
            public String getData() {
                return "Hello from @Bulkhead @Timeout method";
            }
        });
    }

    private CompletionStage<MyConnection> processFallback(boolean fail) {
        return CompletableFuture.completedFuture(new MyConnection() {
            @Override
            public String getData() {
                return "Fallback Hello";
            }
        });
    }
```

Send 10+ parallel requests with fail == true
Expected result:
All requests should go to fallback.

Actual Result:
Random number of requests (close to the number of requests) go to fallback.

https://issues.redhat.com/browse/WFWIP-308

### LINKED ISSUE #199: fallback is always the same for given class.method, even if parameters are different
```java
@ApplicationScoped
public class HelloService {
    @Fallback(fallbackMethod = "fallback")
    public String hello(int counter) throws IOException {
        throw new IOException();
    }

    public String fallback(int counter) {
        return "Hello " + counter;
    }
}
```

When a service like this is invoked with varying values of `counter`, the results must vary as well. However, I always get the same fallback value.

This is because the chain of fault tolerance strategies is cached together with the `InvocationContext` of the call, which includes the method parameters.

### PR DESCRIPTION
**Pull request by Ladicek**
Resolves #197.
Resolves #198.
Resolves #199.

### CODE REVIEW

**Comment by Ladicek** [comment]
Also CC @rhusar @mnovak1

This is best reviewed separately, one commit after the other.

I tried to run the WildFly tests by EAP QE and there's a couple of failures:

```
[ERROR] Failures: 
[ERROR]   MultipleFaultToleranceModuleEarTest.testDeployTwoModuleEarLogsWarning:110 Log does not contain warning that Hystrix was already initialized by first module
[ERROR]   MultipleJarDeploymentTest.testDeploySecondJarLogsHystrixNoConfigChangeWarning:81 Log does not contain WARNING Log: WFLYMPFTEXT0002: Hystrix was already configured! Skipping configuration from deployment - but it should.
[ERROR]   UndeployDeployTest.testDeployTwoWarsLogsWarning:252
[ERROR]   UndeployDeployTest.testNonMPFTDeploymentDoesNotBlockRestartHystrix:225 1 expectation failed.
Response body doesn't match expectation.
Expected: a string containing "Hello from @Timeout method, context = foobar"
  Actual: Fallback Hello, context = foobar

[ERROR]   UndeployDeployTest.testUndeployDeployChangesHystrixConfiguration:145 1 expectation failed.
Response body doesn't match expectation.
Expected: a string containing "Hello from @Timeout method, context = foobar"
  Actual: Fallback Hello, context = foobar
```

Just looking at the names, it seems these tests verify behavior of the old implementation that is no longer present, but it would be great if you guys could verify. It's possible these are genuine bugs.

Also if you could run the MP FT TCK with WildFly with this changeset, that would be great as well. I need to look into updating the Quarkus extension with this, because I had to do some changes in the CDI extension here :-)

**Comment by Ladicek** [comment]
In general, running as many tests as we can with this would be beneficial :-)

**Comment by mnovak1** [comment]
> Just looking at the names, it seems these tests verify behavior of the old implementation that is no longer present, but it would be great if you guys could verify. It's possible these are genuine bugs.

Correct, the other test failures can be ignored as they were relevant just for Hystrix. @tterem has updated branch of the tests for non-hystrix SM FT. @tterem could you link it here, please?

**Comment by tterem** [comment]
Hi @Ladicek,

here is my branch with updated tests:

 https://github.com/tterem/eap-microprofile-test-suite/tree/1428

Tests that were depending on hystrix are removed there. You can try to run your fix against it. Meanwhile I will run as well.

**Comment by Ladicek** [comment]
Cool, thanks.

**Comment by tterem** [comment]
I build your branch locally and I confirm that our MicroProfile testsuite is passing with these changes.

File: implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CompletionStageCircuitBreaker.java [hunk 1]
```diff
@@ -124,24 +116,36 @@ private CompletionException onFailure(State state, Throwable e) {
...
+            CompletableFuture<V> result = new CompletableFuture<>();
 
-            int successes = state.consecutiveSuccesses.incrementAndGet();
-            if (successes >= successThreshold) {
-                long now = System.nanoTime();
-                closedStart = now;
-                previousHalfOpenTime.addAndGet(now - halfOpenStart);
+            delegate.apply(target).whenComplete((value, error) -> {
+                if (error != null) {
+                    metricsRecorder.circuitBreakerFailed();
```
Comment (michalszynkiewicz) [inline implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CompletionStageCircuitBreaker.java]: Maybe worth pulling out the three lines here to a separate method?

**Comment by Ladicek** [comment]
Very nice, thanks! I'm just doing the same, it took me a while :-)

**Comment by rhusar** [comment]
@tterem Great, thanks for the update! I was testing the integration and everything is passing there too.

> [INFO] Tests run: 407, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 406.126 s - in TestSuite

**Comment by Ladicek** [comment]
Awesomesauce!

(I just ran the QE test suite locally and it's passing for me too.)

**Comment by rhusar** [comment]
Are you sure you need the version bump? Nobody cares about internal/private API change.

File: implementation/core/src/main/java/io/smallrye/faulttolerance/core/retry/CompletionStageRetry.java [hunk 2]
```diff
@@ -31,10 +33,8 @@ public CompletionStageRetry(
         return doRetry(ctx, 0, runningStopwatch, null);
     }
 
-    public CompletionStage<V> doRetry(InvocationContext<CompletionStage<V>> target,
-            int attempt,
-            RunningStopwatch stopwatch,
-            Throwable latestFailure) {
+    public CompletionStage<V> doRetry(InvocationContext<CompletionStage<V>> target, int attempt,
```
Comment (michalszynkiewicz) [inline implementation/core/src/main/java/io/smallrye/faulttolerance/core/retry/CompletionStageRetry.java]: was it the auto-formatter? :(

**Comment by rhusar** [comment]
Moreover, @quarkusio will need this fixes anyway so the 4.0.x will be just not in use by anybody.

File: implementation/core/src/main/java/io/smallrye/faulttolerance/core/retry/CompletionStageRetry.java (hunk 2 above)
Comment (rhusar) [reply implementation/core/src/main/java/io/smallrye/faulttolerance/core/retry/CompletionStageRetry.java]: Looks like unintended and unnecessary change.

Comment (rhusar) [reply implementation/core/src/main/java/io/smallrye/faulttolerance/core/retry/CompletionStageRetry.java]: But n.b. given the time press its moot to me.

**Comment by Ladicek** [comment]
I'm not sure about the version bump, but I figured I'd bump a minor as it might affect integrations. Now thinking about it again, the internal API changes only required changing the `FaultToleranceInterceptor`, so they are fully contained and integrations don't need to know. I'll probably remove that version-bumping commit.

File: implementation/core/src/main/java/io/smallrye/faulttolerance/core/retry/CompletionStageRetry.java (hunk 2 above)
Comment (Ladicek) [reply implementation/core/src/main/java/io/smallrye/faulttolerance/core/retry/CompletionStageRetry.java]: This might have actually been me :-) The one line per param format is so inefficient with screen space :-)

File: implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CompletionStageCircuitBreaker.java (hunk 1 above)
Comment (Ladicek) [reply implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CompletionStageCircuitBreaker.java]: I'd prefer not. I tend to not create methods that can possibly only be called from a single place.

**Comment by Ladicek** [comment]
Removed the version-bumping commit.

File: implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CompletionStageCircuitBreaker.java (hunk 1 above)
Comment (michalszynkiewicz) [reply implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CompletionStageCircuitBreaker.java]: you have exactly the same lines in 145-147

Comment (Ladicek) [reply implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CompletionStageCircuitBreaker.java]: Ah, true. That's in fact the same for all `CompletionStage*` strategies, and something I'd like to address in another way (later): the `Invocation` strategy would be, in the async flow, wrapped into an exception-handling strategy, which would catch exceptions thrown by the `Invocation` and propagate them to the `CompletableFuture`. No other `CompletionStage*` strategy would have to do that, anymore.

Comment (Ladicek) [reply implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CompletionStageCircuitBreaker.java]: Filed https://github.com/smallrye/smallrye-fault-tolerance/issues/202

Comment (michalszynkiewicz) [reply implementation/core/src/main/java/io/smallrye/faulttolerance/core/circuit/breaker/CompletionStageCircuitBreaker.java]: :+1:

File: implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceInterceptor.java [hunk 3]
```diff
@@ -136,100 +138,80 @@ public FaultToleranceInterceptor(
...
         }
     }
 
     @SuppressWarnings("unchecked")
-    private <T> T syncFlow(FaultToleranceOperation operation,
-            Class<?> beanClass,
-            InvocationContext invocationContext,
-            MetricsCollector collector,
-            InterceptionPoint point) throws Exception {
+    private <T> T syncFlow(FaultToleranceOperation operation, InvocationContext invocationContext,
```
Comment (michalszynkiewicz) [inline implementation/fault-tolerance/src/main/java/io/smallrye/faulttolerance/FaultToleranceInterceptor.java]: this is much less readable than one arg per line
